"""Traceability reviewer — findings generated by consolidated LLM call."""

from radia_ai.features.jama_requirement_reviewer.models.review_models import (
    RequirementReviewInput,
    ReviewerResult,
    ReviewStatus,
)
from radia_ai.features.jama_requirement_reviewer.reviewers.base import RequirementReviewer


class TraceabilityReviewer(RequirementReviewer):
    name = "traceability"
    reviewer_version = "2.0.0"
    prompt_version = "consolidated.v1"
    standards_version = "rag-live"
    supports_individual_review = True

    def review_requirement(self, payload: RequirementReviewInput) -> ReviewerResult:
        # No deterministic rules — findings come from consolidated LLM call
        return ReviewerResult(
            reviewer=self.name,
            reviewer_version=self.reviewer_version,
            prompt_version=self.prompt_version,
            standards_version=self.standards_version,
            overall=ReviewStatus.ACCEPTABLE,
            findings=[],
        )
