"""
Chat endpoint - RAG question answering.

POST /api/v1/chat

Retrieves relevant chunks from the indexed SharePoint standards documents via
Azure AI Search and generates a grounded answer with Azure OpenAI. The prompt
requires the model to base its answer only on retrieved content, and when
retrieval finds nothing relevant we skip the LLM call entirely and return a
fixed refusal - so every answer is either grounded in a real citation or an
explicit "not found" message, never a hallucinated guess.
"""

from __future__ import annotations

import anyio
from anyio import to_thread
from fastapi import APIRouter, Request, status

from app.core.exceptions import ChatTimeoutError
from app.core.logging import get_logger
from app.prompts.chat_prompts import CHAT_SYSTEM_PROMPT, NO_ANSWER_MESSAGE
from app.rag.service import RAGService, RetrievedContext
from app.schemas.chat import ChatRequest, ChatResponse, CitedChunk
from app.schemas.common import APIResponse
from radia_ai.features.jama_requirement_reviewer.dependencies.container import (
    RAGServiceDep,
    SettingsDep,
)

router = APIRouter()
logger = get_logger(__name__)

# Retrieval and generation each go through Azure SDKs (sync), and the chat
# pipeline is user-facing, so both stages get their own bounded timeout rather
# than inheriting the platform's default request timeout.
_RETRIEVAL_TIMEOUT_SECONDS = 15.0
_GENERATION_TIMEOUT_SECONDS = 45.0
_SNIPPET_LENGTH = 300


@router.post(
    "",
    response_model=APIResponse[ChatResponse],
    summary="Ask a question against indexed documents",
    description=(
        "Submits a question to the RAG pipeline. The pipeline retrieves relevant "
        "document chunks from Azure AI Search and generates a grounded answer using "
        "Azure OpenAI. Citations are returned alongside the answer. When no relevant "
        "document chunks are found, no answer is generated by the LLM and a fixed "
        "'not found' message is returned instead."
    ),
    status_code=status.HTTP_200_OK,
)
async def chat(
    body: ChatRequest,
    request: Request,
    rag_service: RAGServiceDep,
    settings: SettingsDep,
) -> APIResponse[ChatResponse]:
    """RAG chat endpoint - document Q&A grounded in the indexed knowledge base."""
    logger.info(
        "chat_request",
        question_length=len(body.question),
        history_turns=len(body.conversation_history),
        top_k=body.top_k,
    )

    context = await _retrieve(rag_service, body.question, body.top_k)

    if not context.has_context:
        logger.info("chat_no_relevant_chunks", question_length=len(body.question))
        return APIResponse(
            data=_no_answer_response(settings.azure_openai.chat_deployment),
            request_id=request.state.request_id,
        )

    history = [
        {"role": message.role, "content": message.content} for message in body.conversation_history
    ]
    answer = await _generate(rag_service, body.question, context, history)

    # The model can still refuse per the system prompt (e.g. retrieved chunks
    # matched the query but don't actually answer it). Treat that refusal the
    # same as an empty retrieval: no citations attached to an unfounded answer.
    if answer.strip().lower() == NO_ANSWER_MESSAGE.lower():
        return APIResponse(
            data=_no_answer_response(settings.azure_openai.chat_deployment),
            request_id=request.state.request_id,
        )

    response = ChatResponse(
        answer=answer,
        citations=[_to_cited_chunk(chunk) for chunk in context.chunks],
        model=settings.azure_openai.chat_deployment,
        retrieval_count=len(context.chunks),
    )
    return APIResponse(data=response, request_id=request.state.request_id)


async def _retrieve(rag_service: RAGService, question: str, top_k: int) -> RetrievedContext:
    """Run retrieval on the worker threadpool with a bounded timeout."""
    try:
        with anyio.fail_after(_RETRIEVAL_TIMEOUT_SECONDS):
            return await to_thread.run_sync(
                lambda: rag_service.retrieve(question, mode="hybrid", top_k=top_k, diversify=True),
                abandon_on_cancel=True,
            )
    except TimeoutError as e:
        logger.error("chat_retrieval_timeout", timeout_seconds=_RETRIEVAL_TIMEOUT_SECONDS)
        raise ChatTimeoutError(
            "Document retrieval timed out. Please try again.",
            detail={"stage": "retrieval", "timeout_seconds": _RETRIEVAL_TIMEOUT_SECONDS},
        ) from e


async def _generate(
    rag_service: RAGService,
    question: str,
    context: RetrievedContext,
    history: list[dict[str, str]],
) -> str:
    """Run answer generation on the worker threadpool with a bounded timeout."""
    try:
        with anyio.fail_after(_GENERATION_TIMEOUT_SECONDS):
            return await to_thread.run_sync(
                lambda: rag_service.generate_chat_answer(
                    CHAT_SYSTEM_PROMPT,
                    question,
                    context,
                    conversation_history=history,
                ),
                abandon_on_cancel=True,
            )
    except TimeoutError as e:
        logger.error("chat_generation_timeout", timeout_seconds=_GENERATION_TIMEOUT_SECONDS)
        raise ChatTimeoutError(
            "Answer generation timed out. Please try again.",
            detail={"stage": "generation", "timeout_seconds": _GENERATION_TIMEOUT_SECONDS},
        ) from e


def _no_answer_response(model: str) -> ChatResponse:
    """Build the fixed refusal response used whenever no grounding was found."""
    return ChatResponse(
        answer=NO_ANSWER_MESSAGE,
        citations=[],
        model=model,
        retrieval_count=0,
    )


def _to_cited_chunk(chunk: dict[str, object]) -> CitedChunk:
    """Convert a raw retrieved chunk into a citation, truncating its content preview."""
    content = str(chunk.get("content", ""))
    return CitedChunk(
        chunk_id=str(chunk.get("chunk_id", "")),
        source=str(chunk.get("source", "")),
        filename=str(chunk.get("filename", "")),
        section=str(chunk.get("section", "")),
        page_number=chunk.get("page_number"),  # type: ignore[arg-type]
        score=float(chunk.get("score", 0.0)),  # type: ignore[arg-type]
        content_snippet=content[:_SNIPPET_LENGTH],
    )
